---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stroom-efs-claim
  namespace: stroom
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: stroom.gchq.github.io/v1
kind: StroomCluster
metadata:
  name: dev
  namespace: stroom
spec:
  image:
    repository: gchq/stroom
    tag: v7.1-LATEST
  imagePullPolicy: Always
  databaseServerRef:
    serverRef:
      name: dev
  appDatabaseName: stroom
  statsDatabaseName: stats
  ingress:
    hostName: a21ccf6caa1834b769b05b7f7be591c8-790026f529a4503d.elb.eu-west-2.amazonaws.com
    secretName: stroom-tls
    className: nginx
  nodeTerminationPeriodSecs: 300
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  logSender:
    enabled: true
    image:
      repository: gchq/stroom-log-sender
      tag: v2.2.0
    securityContext:
      runAsNonRoot: false
      privileged: true
      runAsUser: 0
      runAsGroup: 0
  nodeSets:
    - name: data
      count: 3
      role: Processing
      localDataVolumeClaim:
        storageClassName: "ebs"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
          #limits:
          #  storage: 1Gi
        #selector:
        #  matchLabels:
        #    app: stroom
        #    component: stroom-node
      ingressEnabled: true
      readinessProbeTimings: {}
      livenessProbeTimings: {}
      memoryOptions:
        initialPercentage: 50
        maxPercentage: 75
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        #limits:
        #  cpu: "2"
        #  memory: 8Gi
      podAnnotations: {}
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector: {}
      tolerations: []
      affinity: {}
    - name: ui
      count: 1
      role: Frontend
      localDataVolumeClaim:
        storageClassName: "ebs"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
          limits:
            storage: 1Gi
        #selector:
        #  matchLabels:
        #    app: stroom
        #    component: stroom-node
      ingressEnabled: true
      ingressAnnotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      memoryOptions:
        initialPercentage: 50
        maxPercentage: 75
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 4Gi
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
  extraVolumes:
    - name: shared
      persistentVolumeClaim:
        claimName: stroom-efs-claim

        #      nfs:
        #server: fs-00a2f743f6b356759.efs.eu-west-2.amazonaws.com
        #path: /data/stroom/stroom-shared
  extraVolumeMounts:
    - name: shared
      mountPath: /stroom/data/data-shared
